---
2-reviewers:
  - '.github/**/*'
  - './*'

M-ci:
  - any: ['.github/**/*']

M-l2geth:
  - any: ['l2geth/**/*']

M-integration:
  - any: ['integration-tests/**/*']

M-batch-submitter:
  - any: ['packages/batch-submitter/**/*']

M-contracts:
  - any: ['packages/contracts/**/*']

M-core-utils:
  - any: ['packages/core-utils/**/*']

M-dtl:
  - any: ['packages/data-transport-layer/**/*']

M-ops:
  - any: ['ops/**/*']
