version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 16
      - yarn
       
  build:
    commands:
        - yarn build:prod
     
artifacts:
  # include all files required to run the application
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
