export type L1orL2Type = 'L2' | 'L1'

export type AddressesType = {
  Lib_AddressManager: string
  L1CrossDomainMessenger: string
  OVM_L1CrossDomainMessenger: string
  Proxy__L1CrossDomainMessenger: string
  Proxy__L1StandardBridge: string
  TK_L1ETH: string
  TK_L2ETH: string
  TK_L1OMG: string
  TK_L2OMG: string
  TK_L1USDT: string
  TK_L2USDT: string
  TK_L1DAI: string
  TK_L2DAI: string
  TK_L1USDC: string
  TK_L2USDC: string
  TK_L1WBTC: string
  TK_L2WBTC: string
  TK_L1REP: string
  TK_L2REP: string
  TK_L1BAT: string
  TK_L2BAT: string
  TK_L1ZRX: string
  TK_L2ZRX: string
  TK_L1SUSHI: string
  TK_L2SUSHI: string
  TK_L1LINK: string
  TK_L2LINK: string
  TK_L1UNI: string
  TK_L2UNI: string
  TK_L1DODO: string
  TK_L2DODO: string
  TK_L1TEST: string
  TK_L2TEST: string
  TK_L1FRAX: string
  TK_L2FRAX: string
  TK_L1FXS: string
  TK_L2FXS: string
  TK_L1BOBA: string
  TK_L2BOBA: string
  TK_L1UST: string
  TK_L2UST: string
  TK_L1BUSD: string
  TK_L2BUSD: string
  TK_L1BNB: string
  TK_L2BNB: string
  TK_L1FTM: string
  TK_L2FTM: string
  TK_L1MATIC: string
  TK_L2MATIC: string
  TK_L2xBOBA: string
  TK_L1UMA: string
  TK_L2UMA: string
  TK_L1DOM: string
  TK_L2DOM: string
  NFT_L1BOBA: string
  NFT_L2BOBA: string
  L1CrossDomainMessengerFast: string
  OVM_L1CrossDomainMessengerFast: string
  Proxy__L1CrossDomainMessengerFast: string
  L2LiquidityPool: string
  L1LiquidityPool: string
  Proxy__L1LiquidityPool: string
  Proxy__L2LiquidityPool: string
  L1MultiMessageRelayerFast: string
  ERC721Registry: string
  DiscretionaryExitBurn: string
  DiscretionaryExitFee: string
  Timelock: string
  GovernorBravoDelegate: string
  GovernorBravoDelegator: string
  GovernorBravoDelegatorV2: string
  BobaFixedSavings: string
  Proxy__BobaFixedSavings: string
  BobaAirdropL1: string
  BobaAirdropL2: string
  L1NFTBridge: string
  L2NFTBridge: string
  Proxy__L1NFTBridge: string
  Proxy__L2NFTBridge: string
  FeedRegistry: string
  BobaStraw_ETHUSD: string
  BobaStraw_BOBAUSD: string
  BobaStraw_WBTCUSD: string
  BobaStraw_OMGUSD: string
  BobaTuringCredit: string
  Proxy__BobaTuringCredit: string
  BobaMonsters: string
  Boba_GasPriceOracle: string
  Proxy__Boba_GasPriceOracle: string
  BobaBillingContract: string
  Proxy__BobaBillingContract: string
  L2StandardTokenFactory: string
  AggregatorHCHepler: string
  Proxy__ETHUSD_AggregatorHC: string
  ETHUSD_AggregatorHC: string
  Proxy__L1ERC1155Bridge: string
  L1ERC1155Bridge: string
  Proxy__L2ERC1155Bridge: string
  L2ERC1155Bridge: string
  Proxy__EthBridgeToBNB: string
  Proxy__EthBridgeToFantom: string
  Proxy__EthBridgeToAvalanche: string
  Proxy__EthBridgeToMoonbeam: string
  EthBridgeToBNB: string
  EthBridgeToFantom: string
  EthBridgeToAvalanche: string
  EthBridgeToMoonbeam: string
  Proxy__BNBBridgeToEth: string
  Proxy__FantomBridgeToEth: string
  Proxy__AvalancheBridgeToEth: string
  Proxy__MoonbeamBridgeToEth: string
  BNBBridgeToEth: string
  FantomBridgeToEth: string
  AvalancheBridgeToEth: string
  MoonbeamBridgeToEth: string
  Eth_TK_BOBA: string
  BNB_TK_BOBA: string
  Avalanche_TK_BOBA: string
  Fantom_TK_BOBA: string
  Moonbeam_TK_BOBA: string
  Layer_Zero_Endpoint: string
  Layer_Zero_ChainId: string
  layerZeroTargetChainID: string
  L1LPAddress: string
  L2LPAddress: string
  L2StandardBridgeAddress: string
  L2MessengerAddress: string
  L2_ETH_Address: string
  L2_BOBA_Address: string
  L1_ETH_Address: string
  NETWORK_NATIVE: string
  L1MessengerAddress: string
  L1FastMessengerAddress: string
  L1StandardBridgeAddress: string
}
