const BobaFixedSavingsABI = [
  'constructor()',
  'event FundsStaked(uint256 stakeId, address account, uint256 amount)',
  'event FundsUnstaked(uint256 stakeId, address account, uint256 amount, uint256 rewards)',
  'event Paused(address account)',
  'event Unpaused(address account)',
  'function FLAT_INTEREST_PER_PERIOD() view returns (uint256)',
  'function LOCK_TIME() view returns (uint256)',
  'function UNSTAKE_TIME() view returns (uint256)',
  'function initialize(address l2BobaAddress, address xBobaAddress)',
  'function l2Boba() view returns (address)',
  'function owner() view returns (address)',
  'function pause()',
  'function paused() view returns (bool)',
  'function personalStakeCount(address) view returns (uint256)',
  'function personalStakePos(address, uint256) view returns (uint256)',
  'function stake(uint256 _amount)',
  'function stakeDataMap(uint256) view returns (uint256 stakeId, address account, uint256 depositAmount, uint256 depositTimestamp, bool isActive)',
  'function stakingCloseTimestamp() view returns (uint256)',
  'function stopStakingContract()',
  'function totalStakeCount() view returns (uint256)',
  'function transferOwnership(address _newOwner)',
  'function unpause()',
  'function unstake(uint256 stakeId)',
  'function xBoba() view returns (address)',
]
export default BobaFixedSavingsABI
