const BOBAABI = [
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) nonpayable returns (bool)',
  'function balanceOf(address account) view returns (uint256)',
  'function burn(uint256 amount) nonpayable',
  'function burnFrom(address account, uint256 amount) nonpayable',
  'function checkpoints(address account, uint32 pos) view returns (tuple)',
  'function decimals() view returns (uint8)',
  'function decreaseAllowance(address spender, uint256 subtractedValue) nonpayable returns (bool)',
  'function delegate(address delegatee) nonpayable',
  'function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) nonpayable',
  'function delegates(address account) view returns (address)',
  'function getCurrentVotes(address account) view returns (uint96)',
  'function getPastTotalSupply(uint256 blockNumber) view returns (uint256)',
  'function getPastVotes(address account, uint256 blockNumber) view returns (uint256)',
  'function getPriorVotes(address account, uint256 blockNumber) view returns (uint96)',
  'function getVotes(address account) view returns (uint256)',
  'function increaseAllowance(address spender, uint256 addedValue) nonpayable returns (bool)',
  'function maxSupply() view returns (uint224)',
  'function name() view returns (string)',
  'function nonces(address owner) view returns (uint256)',
  'function numCheckpoints(address account) view returns (uint32)',
  'function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) nonpayable',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address recipient, uint256 amount) nonpayable returns (bool)',
  'function transferFrom(address sender, address recipient, uint256 amount) nonpayable returns (bool)',
]
export default BOBAABI
