const EthBridgeABI = [
  'function FUNCTION_TYPE_SEND() view returns (uint256)',
  'function NO_EXTRA_GAS() view returns (uint256)',
  'function depositERC20(address _l1Token, address _l2Token, uint256 _amount, address _zroPaymentAddress, bytes _adapterParams, bytes _data) payable',
  'function depositERC20To(address _l1Token, address _l2Token, address _to, uint256 _amount, address _zroPaymentAddress, bytes _adapterParams, bytes _data) payable',
  'function deposits(address , address ) view returns (uint256)',
  'function dstChainId() view returns (uint16)',
  'function failedMessages(uint16 , bytes , uint64 ) view returns (bytes32)',
  'function forceResumeReceive(uint16 _srcChainId, bytes _srcAddress) nonpayable',
  'function getConfig(uint16 _version, uint16 _chainId, address , uint256 _configType) view returns (bytes)',
  'function initialize(address _lzEndpoint, uint16 _dstChainId, address _altL1BridgeAddress) nonpayable',
  'function isTrustedRemote(uint16 _srcChainId, bytes _srcAddress) view returns (bool)',
  'function lzEndpoint() view returns (address)',
  'function lzReceive(uint16 _srcChainId, bytes _srcAddress, uint64 _nonce, bytes _payload) nonpayable',
  'function maxTransferAmountPerDay() view returns (uint256)',
  'function minDstGasLookup(uint16 , uint256 ) view returns (uint256)',
  'function nonblockingLzReceive(uint16 _srcChainId, bytes _srcAddress, uint64 _nonce, bytes _payload) nonpayable',
  'function owner() view returns (address)',
  'function renounceOwnership() nonpayable',
  'function retryMessage(uint16 _srcChainId, bytes _srcAddress, uint64 _nonce, bytes _payload) payable',
  'function setConfig(uint16 _version, uint16 _chainId, uint256 _configType, bytes _config) nonpayable',
  'function setMaxTransferAmountPerDay(uint256 _maxTransferAmountPerDay) nonpayable',
  'function setMinDstGasLookup(uint16 _dstChainId, uint256 _type, uint256 _dstGasAmount) nonpayable',
  'function setReceiveVersion(uint16 _version) nonpayable',
  'function setSendVersion(uint16 _version) nonpayable',
  'function setTrustedRemote(uint16 _srcChainId, bytes _srcAddress) nonpayable',
  'function setUseCustomAdapterParams(bool _useCustomAdapterParams, uint256 _dstGasAmount) nonpayable',
  'function transferOwnership(address newOwner) nonpayable',
  'function transferTimestampCheckPoint() view returns (uint256)',
  'function transferredAmount() view returns (uint256)',
  'function trustedRemoteLookup(uint16 ) view returns (bytes)',
  'function useCustomAdapterParams() view returns (bool)',
]
export default EthBridgeABI
