const GovernorBravoDelegateABI = [
  'function BALLOT_TYPEHASH() view returns (bytes32)',
  'function DOMAIN_TYPEHASH() view returns (bytes32)',
  'function MAX_PROPOSAL_THRESHOLD() view returns (uint256)',
  'function MAX_VOTING_DELAY() view returns (uint256)',
  'function MAX_VOTING_PERIOD() view returns (uint256)',
  'function MIN_PROPOSAL_THRESHOLD() view returns (uint256)',
  'function MIN_VOTING_DELAY() view returns (uint256)',
  'function MIN_VOTING_PERIOD() view returns (uint256)',
  'function admin() view returns (address)',
  'function boba() view returns (address)',
  'function cancel(uint256 proposalId) nonpayable',
  'function castVote(uint256 proposalId, uint8 support) nonpayable',
  'function castVoteBySig(uint256 proposalId, uint8 support, uint8 v, bytes32 r, bytes32 s) nonpayable',
  'function castVoteWithReason(uint256 proposalId, uint8 support, string reason) nonpayable',
  'function execute(uint256 proposalId) payable',
  'function getActions(uint256 proposalId) view returns (address[], uint256[], string[], bytes[])',
  'function getReceipt(uint256 proposalId, address voter) view returns (tuple)',
  'function implementation() view returns (address)',
  'function initialProposalId() view returns (uint256)',
  'function initialize(address timelock_, address bobaToken_, address xbobaToken_, uint256 votingPeriod_, uint256 votingDelay_, uint256 proposalThreshold_) nonpayable',
  'function latestProposalIds(address ) view returns (uint256)',
  'function name() view returns (string)',
  'function pendingAdmin() view returns (address)',
  'function proposalCount() view returns (uint256)',
  'function proposalMaxOperations() view returns (uint256)',
  'function proposalThreshold() view returns (uint256)',
  'function proposals(uint256 ) view returns (uint256, address, uint256, string, uint256, uint256, uint256, uint256, uint256, uint256, bool, bool)',
  'function propose(address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, string description) nonpayable returns (uint256)',
  'function queue(uint256 proposalId) nonpayable',
  'function quorumVotes() view returns (uint256)',
  'function state(uint256 proposalId) view returns (uint8)',
  'function timelock() view returns (address)',
  'function votingDelay() view returns (uint256)',
  'function votingPeriod() view returns (uint256)',
  'function xboba() view returns (address)',
]
export default GovernorBravoDelegateABI
