const L1LiquidityPoolABI = [
  'function L1StandardBridgeAddress() view returns (address)',
  'function L2LiquidityPoolAddress() view returns (address)',
  'function SAFE_GAS_STIPEND() view returns (uint256)',
  'function SETTLEMENT_L2_GAS() view returns (uint32)',
  'function addLiquidity(uint256 _amount, address _tokenAddress) payable',
  'function clientDepositL1(uint256 _amount, address _tokenAddress) payable',
  'function clientDepositL1Batch(tuple[] _tokens) payable',
  'function clientPayL1(address _to, uint256 _amount, address _tokenAddress) nonpayable',
  'function clientPayL1Settlement(address _to, uint256 _amount, address _tokenAddress) nonpayable',
  'function configureFee(uint256 _userRewardMinFeeRate, uint256 _userRewardMaxFeeRate, uint256 _ownerRewardFeeRate) nonpayable',
  'function configureGas(uint32 _l2GasFee, uint256 _safeGas) nonpayable',
  'function currentDepositInfoHash() view returns (bytes32)',
  'function getUserRewardFeeRate(address _l1TokenAddress) view returns (uint256)',
  'function initialize(address _l1CrossDomainMessenger, address _l1CrossDomainMessengerFast, address _L2LiquidityPoolAddress, address _L1StandardBridgeAddress) nonpayable',
  'function l1CrossDomainMessenger() view returns (address)',
  'function lastHashUpdateBlock() view returns (uint256)',
  'function owner() view returns (address)',
  'function ownerRecoverFee(uint256 _amount, address _tokenAddress, address _to) nonpayable',
  'function ownerRewardFeeRate() view returns (uint256)',
  'function pause() nonpayable',
  'function paused() view returns (bool)',
  'function poolInfo(address ) view returns (address, address, uint256, uint256, uint256, uint256, uint256, uint256)',
  'function priorDepositInfoHash() view returns (bytes32)',
  'function rebalanceLP(uint256 _amount, address _tokenAddress) nonpayable',
  'function registerPool(address _l1TokenAddress, address _l2TokenAddress) nonpayable',
  'function relayerMessenger() view returns (address)',
  'function senderMessenger() view returns (address)',
  'function transferOwnership(address _newOwner) nonpayable',
  'function unpause() nonpayable',
  'function updateUserRewardPerShare(address _tokenAddress) nonpayable',
  'function userInfo(address , address ) view returns (uint256, uint256, uint256)',
  'function userRewardMaxFeeRate() view returns (uint256)',
  'function userRewardMinFeeRate() view returns (uint256)',
  'function withdrawLiquidity(uint256 _amount, address _tokenAddress, address _to) nonpayable',
  'function withdrawReward(uint256 _amount, address _tokenAddress, address _to) nonpayable',
]
export default L1LiquidityPoolABI
