const L2LiquidityPoolABI = [
  'function BOBAAddress() view returns (address)',
  'function DAO() view returns (address)',
  'function DEFAULT_FINALIZE_WITHDRAWAL_L1_GAS() view returns (uint32)',
  'function L1LiquidityPoolAddress() view returns (address)',
  'function addLiquidity(uint256 _amount, address _tokenAddress) payable',
  'function billingContractAddress() view returns (address)',
  'function clientDepositL2(uint256 _amount, address _tokenAddress) payable',
  'function clientPayL2(address _to, uint256 _amount, address _tokenAddress) nonpayable',
  'function clientPayL2Batch(tuple[] _tokens) nonpayable',
  'function clientPayL2Settlement(address _to, uint256 _amount, address _tokenAddress) nonpayable',
  'function configureBillingContractAddress(address _billingContractAddress) nonpayable',
  'function configureFee(uint256 _userRewardMinFeeRate, uint256 _userRewardMaxFeeRate, uint256 _ownerRewardFeeRate) nonpayable',
  'function configureFeeExits(uint256 _userRewardMinFeeRate, uint256 _userRewardMaxFeeRate, uint256 _ownerRewardFeeRate) nonpayable',
  'function configureGas(uint32 _l1GasFee) nonpayable',
  'function extraGasRelay() view returns (uint256)',
  'function getFinalizeDepositL1Gas() view returns (uint32)',
  'function getUserRewardFeeRate(address _l2TokenAddress) view returns (uint256)',
  'function initialize(address _l2CrossDomainMessenger, address _L1LiquidityPoolAddress) nonpayable',
  'function messenger() view returns (address)',
  'function owner() view returns (address)',
  'function ownerRecoverFee(uint256 _amount, address _tokenAddress, address _to) nonpayable',
  'function ownerRewardFeeRate() view returns (uint256)',
  'function pause() nonpayable',
  'function paused() view returns (bool)',
  'function poolInfo(address ) view returns (address, address, uint256, uint256, uint256, uint256, uint256, uint256)',
  'function rebalanceLP(uint256 _amount, address _tokenAddress) nonpayable',
  'function registerBOBA(address _BOBAAddress, address _xBOBAAddress) nonpayable',
  'function registerPool(address _l1TokenAddress, address _l2TokenAddress) nonpayable',
  'function transferDAORole(address _newDAO) nonpayable',
  'function transferOwnership(address _newOwner) nonpayable',
  'function unpause() nonpayable',
  'function updateUserRewardPerShare(address _tokenAddress) nonpayable',
  'function userInfo(address , address ) view returns (uint256, uint256, uint256)',
  'function userRewardMaxFeeRate() view returns (uint256)',
  'function userRewardMinFeeRate() view returns (uint256)',
  'function withdrawLiquidity(uint256 _amount, address _tokenAddress, address _to) nonpayable',
  'function withdrawReward(uint256 _amount, address _tokenAddress, address _to) nonpayable',
  'function xBOBAAddress() view returns (address)',
  'function xBOBAStatus(address ) view returns (bool)',
]
export default L2LiquidityPoolABI
