const L2StandardERC20ABI = [
  'constructor(address _l2Bridge, address _l1Token, string _name, string _symbol, uint8 decimals_)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event Burn(address indexed _account, uint256 _amount)',
  'event Mint(address indexed _account, uint256 _amount)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function balanceOf(address account) view returns (uint256)',
  'function burn(address _from, uint256 _amount)',
  'function decimals() view returns (uint8)',
  'function decreaseAllowance(address spender, uint256 subtractedValue) returns (bool)',
  'function increaseAllowance(address spender, uint256 addedValue) returns (bool)',
  'function l1Token() view returns (address)',
  'function l2Bridge() view returns (address)',
  'function mint(address _to, uint256 _amount)',
  'function name() view returns (string)',
  'function supportsInterface(bytes4 _interfaceId) pure returns (bool)',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address recipient, uint256 amount) returns (bool)',
  'function transferFrom(address sender, address recipient, uint256 amount) returns (bool)',
]
export default L2StandardERC20ABI
