const LZEndpointMockABI = [
  'function addrToPackedBytes(address _a) pure returns (bytes)',
  'function blockNextMsg() nonpayable',
  'function estimateFees(uint16 , address , bytes _payload, bool , bytes ) view returns (uint256, uint256)',
  'function forceResumeReceive(uint16 _srcChainId, bytes _srcAddress) nonpayable',
  'function getChainId() view returns (uint16)',
  'function getConfig(uint16 , uint16 , address , uint256 ) pure returns (bytes)',
  'function getInboundNonce(uint16 _chainID, bytes _srcAddress) view returns (uint64)',
  'function getLengthOfQueue(uint16 _srcChainId, bytes _srcAddress) view returns (uint256)',
  'function getOutboundNonce(uint16 _chainID, address _srcAddress) view returns (uint64)',
  'function getReceiveLibraryAddress(address ) view returns (address)',
  'function getReceiveVersion(address ) pure returns (uint16)',
  'function getSendLibraryAddress(address ) view returns (address)',
  'function getSendVersion(address ) pure returns (uint16)',
  'function hasStoredPayload(uint16 _srcChainId, bytes _srcAddress) view returns (bool)',
  'function inboundNonce(uint16 , bytes ) view returns (uint64)',
  'function isReceivingPayload() pure returns (bool)',
  'function isSendingPayload() pure returns (bool)',
  'function lzEndpointLookup(address ) view returns (address)',
  'function mockBlockConfirmations() view returns (uint256)',
  'function mockChainId() view returns (uint16)',
  'function mockLayerZeroVersion() view returns (uint16)',
  'function mockLibraryVersion() view returns (uint16)',
  'function mockOracle() view returns (address)',
  'function mockRelayer() view returns (address)',
  'function mockStaticNativeFee() view returns (uint256)',
  'function msgsToDeliver(uint16 , bytes , uint256 ) view returns (address, uint64, bytes)',
  'function nativeFee() view returns (uint256)',
  'function outboundNonce(uint16 , address ) view returns (uint64)',
  'function packedBytesToAddr(bytes _b) pure returns (address)',
  'function receivePayload(uint16 _srcChainId, bytes _srcAddress, address _dstAddress, uint64 _nonce, uint256 , bytes _payload) nonpayable',
  'function retryPayload(uint16 _srcChainId, bytes _srcAddress, bytes _payload) nonpayable',
  'function send(uint16 _chainId, bytes _destination, bytes _payload, address , address , bytes _adapterParams) payable',
  'function setConfig(uint16 , uint16 , uint256 , bytes ) nonpayable',
  'function setDestLzEndpoint(address destAddr, address lzEndpointAddr) nonpayable',
  'function setEstimatedFees(uint256 _nativeFee, uint256 _zroFee) nonpayable',
  'function setReceiveVersion(uint16 ) nonpayable',
  'function setSendVersion(uint16 ) nonpayable',
  'function storedPayload(uint16 , bytes ) view returns (uint64, address, bytes32)',
  'function zroFee() view returns (uint256)',
]
export default LZEndpointMockABI
