const NFTMonsterV2ABI = [
  'function MAX_MINT_IN_PUBLIC() view returns (uint256)',
  'function PRICE() view returns (uint256)',
  'function ROYALTY_PERCENTAGE() view returns (uint256)',
  'function amountMintedInPublicSale(address ) view returns (uint256)',
  'function approve(address to, uint256 tokenId) nonpayable',
  'function availableTokenCount() view returns (uint256)',
  'function balanceOf(address owner) view returns (uint256)',
  'function bridgeExtraData(uint256 tokenId) view returns (bytes)',
  'function burn(uint256 tokenId) nonpayable',
  'function exists(uint256 tokenId) view returns (bool)',
  'function getApproved(uint256 tokenId) view returns (address)',
  'function isApprovedForAll(address owner, address operator) view returns (bool)',
  'function mint(uint256 _count) payable',
  'function name() view returns (string)',
  'function owner() view returns (address)',
  'function ownerOf(uint256 tokenId) view returns (address)',
  'function paused() view returns (bool)',
  'function price(uint256 _count) pure returns (uint256)',
  'function projectOwners(uint256 ) view returns (address)',
  'function recoverERC20(address tokenAddress, uint256 tokenAmount) nonpayable',
  'function recoverERC721(address tokenAddress, uint256 tokenId_) nonpayable',
  'function renounceOwnership() nonpayable',
  'function royaltyInfo(uint256 _tokenId, uint256 _salePrice) view returns (address, uint256)',
  'function safeTransferFrom(address from, address to, uint256 tokenId) nonpayable',
  'function safeTransferFrom(address from, address to, uint256 tokenId, bytes _data) nonpayable',
  'function setApprovalForAll(address operator, bool approved) nonpayable',
  'function startTrading() nonpayable',
  'function supportsInterface(bytes4 _interfaceId) view returns (bool)',
  'function symbol() view returns (string)',
  'function tokenCount() view returns (uint256)',
  'function tokenURI(uint256 tokenId) view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transferFrom(address from, address to, uint256 tokenId) nonpayable',
  'function transferOwnership(address newOwner) nonpayable',
  'function withdraw() nonpayable',
]
export default NFTMonsterV2ABI
