const TeleportationABI = [
  'event AssetBalanceWithdrawn(address indexed token, address indexed owner, uint256 balance)',
  'event AssetReceived(address token, uint32 sourceChainId, uint32 indexed toChainId, uint256 indexed depositId, address indexed emitter, uint256 amount)',
  'event DisbursementFailed(uint256 indexed depositId, address indexed to, uint256 amount, uint32 sourceChainId)',
  'event DisbursementRetrySuccess(uint256 indexed depositId, address indexed to, uint256 amount, uint32 sourceChainId)',
  'event DisbursementSuccess(uint256 indexed depositId, address indexed to, address indexed token, uint256 amount, uint32 sourceChainId)',
  'event DisburserTransferred(address newDisburser)',
  'event MaxDepositAmountSet(address token, uint32 toChainId, uint256 previousAmount, uint256 newAmount)',
  'event MaxTransferAmountPerDaySet(address token, uint32 toChainId, uint256 previousAmount, uint256 newAmount)',
  'event MinDepositAmountSet(address token, uint32 toChainId, uint256 previousAmount, uint256 newAmount)',
  'event OwnershipTransferred(address newOwner)',
  'event Paused(address account)',
  'event TokenSupported(address indexed token, uint32 indexed toChainId, bool supported)',
  'event Unpaused(address account)',
  'function addSupportedToken(address _token, uint32 _toChainId, uint256 _minDepositAmount, uint256 _maxDepositAmount, uint256 _maxTransferAmountPerDay)',
  'function disburseAsset(tuple(address token, uint256 amount, address addr, uint32 sourceChainId, uint256 depositId)[] _disbursements) payable',
  'function disburser() view returns (address)',
  'function failedNativeDisbursements(uint256) view returns (bool failed, tuple(address token, uint256 amount, address addr, uint32 sourceChainId, uint256 depositId) disbursement)',
  'function initialize()',
  'function multicall(bytes[] data) returns (bytes[] results)',
  'function owner() view returns (address)',
  'function pause()',
  'function paused() view returns (bool)',
  'function removeSupportedToken(address _token, uint32 _toChainId)',
  'function retryDisburseNative(uint256[] _depositIds) payable',
  'function setMaxAmount(address _token, uint32 _toChainId, uint256 _maxDepositAmount)',
  'function setMaxTransferAmountPerDay(address _token, uint32 _toChainId, uint256 _maxTransferAmountPerDay)',
  'function setMinAmount(address _token, uint32 _toChainId, uint256 _minDepositAmount)',
  'function supportedTokens(address, uint32) view returns (bool supported, uint256 minDepositAmount, uint256 maxDepositAmount, uint256 maxTransferAmountPerDay, uint256 transferredAmount, uint256 transferTimestampCheckPoint)',
  'function teleportAsset(address _token, uint256 _amount, uint32 _toChainId) payable',
  'function totalDeposits(uint256) view returns (uint256)',
  'function totalDisbursements(uint256) view returns (uint256)',
  'function transferDisburser(address _newDisburser)',
  'function transferOwnership(address _newOwner)',
  'function unpause()',
  'function withdrawBalance(address _token)',
]
export default TeleportationABI
