const TeleportationABI = [
  'function addSupportedToken(address _token, uint32 _toChainId, uint256 _minDepositAmount, uint256 _maxDepositAmount, uint256 _maxTransferAmountPerDay) nonpayable',
  'function disburseAsset(tuple[] _disbursements) payable',
  'function disburser() view returns (address)',
  'function failedNativeDisbursements(uint256 ) view returns (bool, tuple)',
  'function initialize() nonpayable',
  'function multicall(bytes[] data) nonpayable returns (bytes[])',
  'function owner() view returns (address)',
  'function pause() nonpayable',
  'function paused() view returns (bool)',
  'function removeSupportedToken(address _token, uint32 _toChainId) nonpayable',
  'function retryDisburseNative(uint256[] _depositIds) payable',
  'function setMaxAmount(address _token, uint32 _toChainId, uint256 _maxDepositAmount) nonpayable',
  'function setMaxTransferAmountPerDay(address _token, uint32 _toChainId, uint256 _maxTransferAmountPerDay) nonpayable',
  'function setMinAmount(address _token, uint32 _toChainId, uint256 _minDepositAmount) nonpayable',
  'function supportedTokens(address , uint32 ) view returns (bool, uint256, uint256, uint256, uint256, uint256)',
  'function teleportAsset(address _token, uint256 _amount, uint32 _toChainId) payable',
  'function totalDeposits(uint256 ) view returns (uint256)',
  'function totalDisbursements(uint256 ) view returns (uint256)',
  'function transferDisburser(address _newDisburser) nonpayable',
  'function transferOwnership(address _newOwner) nonpayable',
  'function unpause() nonpayable',
  'function withdrawBalance(address _token) nonpayable',
]
export default TeleportationABI
