const WAGMIv0ABI = [
  'function collateralPerPair() view returns (uint256)',
  'function collateralToken() view returns (address)',
  'function create(uint256 tokensToCreate) nonpayable returns (uint256)',
  'function customAncillaryData() view returns (bytes)',
  'function earlyExpirationTimestamp() view returns (uint64)',
  'function enableEarlyExpiration() view returns (bool)',
  'function expirationTimestamp() view returns (uint64)',
  'function expire() nonpayable',
  'function expiryPercentLong() view returns (uint256)',
  'function expiryPrice() view returns (int256)',
  'function financialProductLibrary() view returns (address)',
  'function finder() view returns (address)',
  'function getCurrentTime() view returns (uint256)',
  'function getEarlyExpirationAncillaryData() view returns (bytes)',
  'function getPositionTokens(address sponsor) view returns (uint256, uint256)',
  'function ignoreEarlyExpirationPrice() pure returns (int256)',
  'function isContractEarlyExpired() nonpayable returns (bool)',
  'function longToken() view returns (address)',
  'function optimisticOracleLivenessTime() view returns (uint256)',
  'function optimisticOracleProposerBond() view returns (uint256)',
  'function pairName() view returns (string)',
  'function priceIdentifier() view returns (bytes32)',
  'function proposerReward() view returns (uint256)',
  'function receivedSettlementPrice() view returns (bool)',
  'function redeem(uint256 tokensToRedeem) nonpayable returns (uint256)',
  'function requestEarlyExpiration(uint64 _earlyExpirationTimestamp) nonpayable',
  'function setCurrentTime(uint256 time) nonpayable',
  'function settle(uint256 longTokensToRedeem, uint256 shortTokensToRedeem) nonpayable returns (uint256)',
  'function shortToken() view returns (address)',
  'function timerAddress() view returns (address)',
]
export default WAGMIv0ABI
