name: E2E Playwright Test
permissions: read-all

on: 
  push: 
    branches:
      - 'main'
      - 'develop'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  e2e-test:
    name: Playwright Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.17.0
          cache: 'yarn'
      - name: Install yarn dependencies
        run: yarn
      - name: Build Gateway
        working-directory: ./
        run: |
          yarn && yarn build:prod
        env:
          REACT_APP_POLL_INTERVAL: 15000
          REACT_APP_GAS_POLL_INTERVAL: 30000
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_WALLET_VERSION: 0.14.9
          REACT_APP_ENV: local
          REACT_APP_ENABLE_ANCHORAGE: true
          REACT_APP_WC_PROJECT_ID: ${{secrets.WC_PROJECT_ID}}
          REACT_APP_GA4_MEASUREMENT_ID: ${{secrets.GA4_MEASUREMENT_ID}}
          REACT_APP_SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install pnpm deps e2e tests
        working-directory: ./e2e-tests
        run: |
          npm install -g pnpm && pnpm install --frozen-lockfile && npx playwright install
      - name: Run E2E TEST
        working-directory: ./e2e-tests
        run: |
          pnpm start:server & pnpm test:headless
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          NETWORK: 'sepolia'
          SECRET_WORDS: ${{secrets.SECRET_WORDS}}
          METAMASK_VERSION: 10.25.0
      - name: Upload Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-reports
          retention-days: 3
          path: |
            ./e2e-tests/videos/
            ./e2e-tests/playwright-report/
            ./e2e-tests/test-results/
        continue-on-error: true
