name: End2End test (non-headless)
permissions: read-all

on:
  pull_request:

jobs:
  End-to-End-Test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.16.0
          cache: 'yarn'
      - name: Setup Cache Node Modules, Cypress
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: yarn
      - uses: actions/cache/save@v4
        if: ${{steps.cache-node-modules.outputs.cache-hit != 'true'}}
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb
      - name: Run E2E Test (non-headless)
        working-directory: ./
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox & yarn test:integration
        env:
          REACT_APP_POLL_INTERVAL: 15000
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_WALLET_VERSION: 0.9.1
          REACT_APP_ENV: prod
          REACT_APP_STATUS: normal
          CYPRESS_REMOTE_DEBUGGING_PORT: 9222
          NETWORK_NAME: 'goerli'
          SECRET_WORDS: ${{secrets.SECRET_WORDS}}
          DISPLAY: :0.0
          CYPRESS_ENABLE_VIDEO: true
      - name: Upload Archive e2e artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-archive
          path: |
            ./cypress/videos/
            ./cypress/screenshots/
        continue-on-error: true
